# Generated by Django 5.2.8 on 2025-12-08 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'post'], name='like_user_post_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-post_id'], name='post_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-like_count', '-post_id'], name='post_ranking_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-time'], name='post_time_idx'),
        ),
    ]
