# Generated by Django 5.2.9 on 2025-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
